-- =====================================================================
-- Estructura inicial - Gestión de Empleados (H2 compatible)
-- =====================================================================

DROP TABLE IF EXISTS EMPLEADO;
DROP TABLE IF EXISTS DEPARTAMENTO;
DROP TABLE IF EXISTS PUESTO;

-- DEPARTAMENTO
CREATE TABLE DEPARTAMENTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL
);

-- PUESTO
CREATE TABLE PUESTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL
);

-- EMPLEADO
CREATE TABLE EMPLEADO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EDAD INT NOT NULL,
    FECHA_INGRESO DATE NOT NULL,
    SALARIO FLOAT NOT NULL,
    EMPLEADO_FIJO BOOLEAN NOT NULL,
    DEPARTAMENTO_ID INT,
    PUESTO_ID INT,
    CONSTRAINT FK_EMPLEADO_DEPARTAMENTO FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES DEPARTAMENTO(ID),
    CONSTRAINT FK_EMPLEADO_PUESTO FOREIGN KEY (PUESTO_ID) REFERENCES PUESTO(ID)
);

-- Índices opcionales
CREATE INDEX IF NOT EXISTS IX_EMPLEADO_DEPARTAMENTO ON EMPLEADO(DEPARTAMENTO_ID);
CREATE INDEX IF NOT EXISTS IX_EMPLEADO_PUESTO ON EMPLEADO(PUESTO_ID);
